#!/usr/bin/env python3
"""FigmaWave/Weavy credit drain supervisor.

This supervisor handles the local, durable parts of the drain loop:

1) status: check account credits and active/in-flight jobs.
2) prepare-batch: prepare one job per credited FigmaWave account concurrently.
3) complete-batch: after reference images are generated by OpenClaw, submit the
   prepared jobs concurrently to FigmaWave/Weavy and optionally mark successful
   completions READY_TO_UPLOAD after basic media validation.

Reference image generation is intentionally not done here because the project
pipeline depends on OpenClaw's image_generate tool. Use the manifest emitted by
prepare-batch to generate references, save them as validated 9:16 images, then
call complete-batch with --refs-json or --refs-dir.
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipeline.config import ACTIVE_STATUSES, RUNS_CSV, load_env  # noqa: E402
from pipeline.providers.figmawave import figmawave_auths, figmawave_remaining_credits  # noqa: E402
from pipeline.state import active_generations_from_state, state_load  # noqa: E402

PY = sys.executable
DATA_DIR = ROOT / "data"
DRAIN_DIR = DATA_DIR / "drain_runs"


def account_worker(label: str) -> str:
    m = re.search(r"(\d+)$", label or "")
    return f"W{m.group(1)}" if m else label or "default"


def load_rows() -> list[dict[str, str]]:
    if not RUNS_CSV.exists():
        return []
    with RUNS_CSV.open(newline="", encoding="utf-8", errors="replace") as f:
        return [dict(r) for r in csv.DictReader(f) if r.get("job_id")]


def active_auth_labels(rows: list[dict[str, str]]) -> set[str]:
    labels: set[str] = set()
    active = set(ACTIVE_STATUSES) | {"STARTED", "NEEDS_REFERENCE_IMAGE"}
    for row in rows:
        if (row.get("status") or "").strip().upper() in active:
            label = (row.get("provider_auth_label") or "").strip()
            if label:
                labels.add(label)
    return labels


def credit_snapshot() -> list[dict[str, Any]]:
    load_env()
    rows = load_rows()
    active_labels = active_auth_labels(rows)
    active_items = active_generations_from_state(state_load())
    out = []
    for auth in figmawave_auths():
        label = auth.get("label") or ""
        item: dict[str, Any] = {
            "label": label,
            "email": auth.get("email", ""),
            "worker": account_worker(label),
            "recipe_id": auth.get("recipe_id", ""),
            "active": label in active_labels,
        }
        try:
            credits = figmawave_remaining_credits(auth)
            item["credits"] = credits
            item["estimated_generations"] = credits // 10
        except Exception as e:  # keep status robust
            item["error"] = str(e)[:500]
        out.append(item)
    return [{"active_generations": active_items}, *out]


def eligible_accounts(min_credits: int, labels: list[str] | None = None, include_active: bool = False) -> list[dict[str, Any]]:
    snap = credit_snapshot()[1:]
    wanted = set(labels or [])
    accounts = []
    for item in snap:
        if wanted and item["label"] not in wanted:
            continue
        if item.get("error"):
            continue
        if not include_active and item.get("active"):
            continue
        if int(item.get("credits") or 0) >= min_credits:
            accounts.append(item)
    return accounts


def run_prepare(account: dict[str, Any], run_dir: Path, max_active: int) -> dict[str, Any]:
    label = account["label"]
    worker = account["worker"]
    env = os.environ.copy()
    env.update({
        "VIDEO_PROVIDER": "figmawave",
        "MAX_ACTIVE_GENERATIONS": str(max_active),
        "MOTION_WORKER_ID": worker,
        "FIGMAWAVE_AUTH_LABEL": label,
    })
    log_path = run_dir / f"prepare_{worker}_{label}.log"
    cmd = [PY, "motion_pipeline.py", "prepare"]
    started = time.time()
    proc = subprocess.run(cmd, cwd=ROOT, env=env, text=True, capture_output=True)
    log_path.write_text(proc.stdout + ("\nSTDERR:\n" + proc.stderr if proc.stderr else ""), encoding="utf-8")
    result: dict[str, Any] = {
        "label": label,
        "worker": worker,
        "returncode": proc.returncode,
        "log_path": str(log_path),
        "duration_seconds": round(time.time() - started, 2),
    }
    if proc.returncode != 0:
        result["error"] = (proc.stderr or proc.stdout)[-1500:]
        return result
    try:
        payload = json.loads(proc.stdout)
    except Exception as e:
        result["error"] = f"Could not parse prepare stdout as JSON: {e}; tail={(proc.stdout or '')[-1000:]}"
        return result
    result.update(payload)
    result["job_dir"] = str(ROOT / "downloads" / payload["job_id"])
    result["generated_reference_path"] = str(ROOT / "downloads" / payload["job_id"] / "generated_reference.jpg")
    return result


def prepare_batch(args: argparse.Namespace) -> dict[str, Any]:
    load_env()
    labels = args.labels.split(",") if args.labels else None
    accounts = eligible_accounts(args.min_credits, labels=labels, include_active=args.include_active)
    accounts = accounts[: args.limit]
    stamp = time.strftime("%Y%m%d%H%M%S", time.gmtime())
    run_dir = DRAIN_DIR / f"figmawave_drain_{stamp}"
    run_dir.mkdir(parents=True, exist_ok=True)
    manifest: dict[str, Any] = {
        "created_at_utc": stamp,
        "run_dir": str(run_dir),
        "mode": "prepare-batch",
        "min_credits": args.min_credits,
        "limit": args.limit,
        "accounts": accounts,
        "jobs": [],
    }
    if not accounts:
        manifest["note"] = "No eligible accounts."
    with ThreadPoolExecutor(max_workers=max(1, len(accounts))) as pool:
        futures = [pool.submit(run_prepare, a, run_dir, max(1, args.limit)) for a in accounts]
        for fut in as_completed(futures):
            manifest["jobs"].append(fut.result())
    manifest_path = run_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    manifest["manifest_path"] = str(manifest_path)
    return manifest


def refs_from_args(args: argparse.Namespace) -> dict[str, str]:
    refs: dict[str, str] = {}
    if args.refs_json:
        raw = json.loads(Path(args.refs_json).read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            refs.update({str(k): str(v) for k, v in raw.items()})
        elif isinstance(raw, list):
            for item in raw:
                refs[str(item["job_id"])] = str(item["reference_path"])
    if args.refs_dir:
        d = Path(args.refs_dir)
        for p in d.glob("*"):
            if p.is_file():
                m = re.search(r"(\d{14}-[0-9a-f]{6})", p.name)
                if m:
                    refs.setdefault(m.group(1), str(p))
    return refs


def run_complete(job: dict[str, Any], ref_path: str, run_dir: Path, max_active: int, auto_ready: bool) -> dict[str, Any]:
    label = job["label"]
    worker = job["worker"]
    job_id = job["job_id"]
    env = os.environ.copy()
    env.update({
        "VIDEO_PROVIDER": "figmawave",
        "MAX_ACTIVE_GENERATIONS": str(max_active),
        "MOTION_WORKER_ID": worker,
        "FIGMAWAVE_AUTH_LABEL": label,
    })
    log_path = run_dir / f"complete_{worker}_{label}_{job_id}.log"
    cmd = [PY, "motion_pipeline.py", "complete", job_id, ref_path, "--provider", "figmawave"]
    started = time.time()
    proc = subprocess.run(cmd, cwd=ROOT, env=env, text=True, capture_output=True)
    log_path.write_text(proc.stdout + ("\nSTDERR:\n" + proc.stderr if proc.stderr else ""), encoding="utf-8")
    result: dict[str, Any] = {
        "job_id": job_id,
        "label": label,
        "worker": worker,
        "returncode": proc.returncode,
        "log_path": str(log_path),
        "duration_seconds": round(time.time() - started, 2),
    }
    if proc.returncode != 0:
        result["error"] = (proc.stderr or proc.stdout)[-2000:]
        return result
    try:
        result["complete_payload"] = json.loads(proc.stdout)
    except Exception:
        result["complete_stdout_tail"] = proc.stdout[-1000:]
    if auto_ready:
        ready_cmd = [PY, "motion_pipeline.py", "set-status", job_id, "READY_TO_UPLOAD", "--note", "Auto-ready after FigmaWave drain completion; basic provider completion passed."]
        ready = subprocess.run(ready_cmd, cwd=ROOT, text=True, capture_output=True)
        result["auto_ready_returncode"] = ready.returncode
        result["auto_ready_output"] = (ready.stdout or ready.stderr)[-1000:]
    return result


def complete_batch(args: argparse.Namespace) -> dict[str, Any]:
    manifest_path = Path(args.manifest)
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    refs = refs_from_args(args)
    run_dir = Path(manifest.get("run_dir") or manifest_path.parent)
    jobs = [j for j in manifest.get("jobs", []) if j.get("job_id") and j.get("returncode") == 0]
    selected = []
    missing = []
    for job in jobs:
        ref = refs.get(job["job_id"]) or job.get("generated_reference_path")
        if ref and Path(ref).exists():
            selected.append((job, ref))
        else:
            missing.append(job["job_id"])
    result: dict[str, Any] = {
        "manifest": str(manifest_path),
        "mode": "complete-batch",
        "missing_reference_jobs": missing,
        "jobs": [],
    }
    with ThreadPoolExecutor(max_workers=max(1, len(selected))) as pool:
        futures = [pool.submit(run_complete, job, ref, run_dir, max(1, args.limit or len(selected)), args.auto_ready) for job, ref in selected]
        for fut in as_completed(futures):
            result["jobs"].append(fut.result())
    out_path = run_dir / f"complete_summary_{time.strftime('%Y%m%d%H%M%S', time.gmtime())}.json"
    out_path.write_text(json.dumps(result, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    result["summary_path"] = str(out_path)
    return result


def main() -> int:
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)

    sub.add_parser("status", help="Print FigmaWave credits and active jobs.")

    prep = sub.add_parser("prepare-batch", help="Prepare one job per eligible credited account concurrently.")
    prep.add_argument("--limit", type=int, default=6)
    prep.add_argument("--min-credits", type=int, default=10)
    prep.add_argument("--labels", help="Comma-separated labels, e.g. figmawave-3,figmawave-4")
    prep.add_argument("--include-active", action="store_true", help="Do not skip accounts with active rows. Use carefully.")

    comp = sub.add_parser("complete-batch", help="Submit prepared jobs concurrently after reference images exist.")
    comp.add_argument("manifest")
    comp.add_argument("--refs-json", help="JSON map/list of job_id to reference path.")
    comp.add_argument("--refs-dir", help="Directory containing files named with job_id.")
    comp.add_argument("--limit", type=int, default=0)
    comp.add_argument("--auto-ready", action="store_true", help="Mark successful completes READY_TO_UPLOAD without visual review.")

    args = ap.parse_args()
    if args.cmd == "status":
        payload = credit_snapshot()
    elif args.cmd == "prepare-batch":
        payload = prepare_batch(args)
    elif args.cmd == "complete-batch":
        payload = complete_batch(args)
    else:
        raise AssertionError(args.cmd)
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
